name: GitHub Copilot Code Review

on:
  push:
    branches: [ main, master ]

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install GitHub Copilot CLI
        run: |
          npm install -g @githubnext/github-copilot-cli

      - name: Run GitHub Copilot Review
        run: |
          copilot review --output review_report.txt

      - name: Upload Review Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: copilot-review-report
          path: review_report.txt